// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkgetgcemutinqscesjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZ2V0Z2NlbXV0aW5xc2Nlc2p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjA2ODMsImV4cCI6MjA2ODgzNjY4M30.9p1FKalfuGg_-aE1dqVLHhN46mQDA3-xQYmbI6tD-8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});