// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://reomrtpxmbaxzqavreil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlb21ydHB4bWJheHpxYXZyZWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTgzMDAsImV4cCI6MjA2ODA3NDMwMH0.2ku0jwcILH7hKn7OcDn3Xe6xjSiYnR-aY9Gbf5MlJnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});